---
pipeline:
  build:
    image: rancher/dapper:1.11.2
    commands:
      - dapper ci
    when:
      ref:
        exclude: [ regs/tags/*stable* ]

  promote_stable:
    image: rancher/dapper:1.11.2
    commands:
      - dapper promote
    when:
      branch: master
      event: tag
      ref:
        include: [ regs/tags/*stable* ]

  publish-latest:
    image: plugins/gcs
    source: charts/latest
    target: releases.rancher.com/server-charts/latest
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    secrets:
      - source: google_auth_key
        target: GOOGLE_CREDENTIALS
    when:
      branch: master
      event: tag
      ref:
        exclude: [ regs/tags/*stable* ]

  publish-stable:
    image: plugins/gcs
    source: charts/stable
    target: releases.rancher.com/server-charts/stable
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    secrets:
      - source: google_auth_key
        target: GOOGLE_CREDENTIALS
    when:
      branch: master
      event: tag
      ref:
        include: [ regs/tags/*stable* ]
